spring:
  application:
    name: Config-Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Endy0611/Config_Server.git
          # file://${user.home}/config-repo for local testing
          search-paths: config-repo #find folder in repo
          default-label: main # branch
          clone-on-start: true # clone at start
encrypt:
  key: ${ENCRYPT_KEY}
server:
  port: 8888
