spring:
  application:
    name: Config-Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Endy0611/Config_Server.git
          search-paths: config-repo
          default-label: main
          clone-on-start: true

server:
  port: 8888
